config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  resources :flights, only: [:index]
  resources :bookings, only: [:new, :show, :create]
  resources :passengers, only: [:new]
  get 'flights', to: 'flights#index'
  post 'bookings/new', to: 'bookings#create'
end

app/models/airport.rb
class Airport < ApplicationRecord
  validates :name, presence: true
  validates :code,  length: { is: 3 }, 
                    uniqueness: true,
                    format: {  with: /\A[a-zA-Z]{3}\z/}
  before_save :upcase_code

  has_many :departures, class_name: "Flight", foreign_key: "departure_id"
  has_many :arrivals,   class_name: "Flight", foreign_key: "arrival_id"

  private

  def upcase_code
    self.code = code.upcase
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :flight, presence: true
  validates :passengers, presence: true
  
  has_many :passengers
  belongs_to :flight
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  validates :departure,       presence: true
  validates :arrival,         presence: true
  validates :departure_time,  presence: true

  belongs_to :departure, class_name: "Airport"
  belongs_to :arrival, class_name: "Airport"
  has_many :bookings

  def self.departure_list
    select(:departure_id).distinct
  end

  def self.arrival_list
    select(:arrival_id).distinct
  end

  def self.date_list
    date = Flight.all.order(departure_time: :asc)
    date.map { |f| f.departure_time.strftime("%b %d %Y") }.uniq
  end

  def self.lookup(departure, arrival, day)
    Flight.where(departure_id: departure,
                 arrival_id: arrival,
                 departure_time: day_range(day))
  end

  private

  def self.day_range(date)
    unless date.nil?
      date = date.to_date
      date.beginning_of_day..date.end_of_day
    end
  end

end

app/models/passenger.rb
class Passenger < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 50 }
  valid_email_address = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*[a-z]+\z/i
  validates :email, presence: true, format: { with: valid_email_address },
                    length: { maximum: 255 }

  belongs_to :booking, optional: true
  has_one :flight, through: :booking

  before_save :downcase_email

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/airport_controller.rb
class AirportController < ApplicationController

  def new
    @airport = Airport.new
  end

  def create
    @airport = Airport.create(airport_params)
  end

private

  def airport_params
    params.require(:airports).permit(:airport)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    params[:passengers].to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      # Confirmation Email
      @booking.passengers.each do |passenger|
        BookingMailer.booking_email(passenger, @booking.id).deliver_now
      end
      redirect_to @booking
    else
      flash.now[:danger] = 'Unable to complete transatcion'
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, :passengers_attributes => [:name, :email])
  end

end

app/controllers/flight_controller.rb
class FlightController < ApplicationController

  def new
    @flight = Flight.new
  end

  def create
    @flight = Flight.create(flight_params)
  end

  def index
    @departures = Flight.select("DISTINCT departure_airport_id").all.map do |df|
      [df.departure_airport.name, df.departure_airport.id]
    end

    @arrivals = Flight.select("DISTINCT arrival_airport_id").all.map do |af|
      [af.arrival_airport.name, af.arrival_airport.id]
    end
    
    @seats = [1, 2, 3, 4]

    @date = Array.new
    Flight.all.each do |f| 
      take_off_date = f.take_off.strftime("%B %d")
      @date << take_off_date unless @date.include?(take_off_date)
    end
  
    if params[:departure_id]
      @search = Flight.where(departure_airport_id: "#{params[:departure_id]}")
    end

  end

  def show
  end

private
  
  def flight_params
    params.require(:flights).allow(:departure_airport_id, :arrival_airport_id,
                                  :take_off, :duration)
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @departures = Flight.departure_list.map { |d| [d.departure.name, d.departure_id] }
    @arrivals = Flight.arrival_list.map { |a| [a.arrival.name, a.arrival_id] }
    @dates = Flight.date_list
    @passengers = [1, 2, 3, 4]

    @flights = Flight.lookup(params[:departing],
                             params[:arriving],
                             params[:date])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<% if @booking.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@booking.errors.count, "error") %> prohibited
      this user from being saved:
    </h2>

    <ul>
    <% @booking.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="section">
  <%= form_for @booking, html: { class: 'columns' } do |booking_form|%>
    <%= booking_form.fields_for :passengers do |p| %>
      <div class="column bg-translucent has-margins">
        <%= p.label :name, "Passenger Name", class: 'label' %>
        <%= p.text_field :name, class: 'input', required: true %>
        
        <%= p.label :email, class: 'label' %>
        <%= p.text_field :email, class: 'input', required: true %>
      </div>
    <% end %>
</div>

<div class="column has-text-centered">
    <%= booking_form.hidden_field "flight_id", value: params[:selected] %>
    <%= booking_form.submit "Book Flight", name: nil, class: 'button is-primary is-large' %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="section">
  <div class="columns">
    <div class="column bg-translucent has-text-centered has-margins">
      <h1>Booking Confirmed!</h1>
    </div>
  </div>
  <div class="columns">
    <% @booking.passengers.each_with_index do |passenger, i| %>
      <div class="column bg-translucent has-text-centered has-margins">
        <h2>Passenger <%= i+1 %>: <%= passenger.name %></h2>
        <h2>Email: <%= passenger.email %></h2>
      </div>
    <% end %>
      <div class="column bg-translucent has-text-centered has-margins">
        <h2><%= @booking.flight.departure.name %></h2>
        <h2><%= @booking.flight.departure_time.strftime("%I:%M %P on %b %d %Y") %></h2>
      </div>
  </div>
</div>

app/views/flight/index.html.erb
<h1>Flight Index</h1>
<div class="container">

<%= form_tag flights_path, method: 'get' do %>
  <div class="form_select" id="departure_select">
    <%= label_tag "Departure Airport" %>
    <%= select_tag(:departure_id, options_for_select(@departures)) %>
  </div>
  <div class="form_select" id="arrival_select">
    <%= label_tag "Arrival Airport" %>
    <%= select_tag(:arrival_id, options_for_select(@arrivals)) %>
  </div>
  <div class="form_select" id="passengers_select">
    <%= label_tag "Passengers" %>
    <%= select_tag(:seats, options_for_select(@seats)) %>
  </div>
  <div class="form_select" id="flight_date_select">
    <%= label_tag "Flight Date" %>
    <%= select_tag(:take_off, options_for_select(@date)) %>
  </div>
  <div>
    <%= submit_tag "Search for Flight" %>
  </div>
<% end %>

app/views/flights/index.html.erb
<section class="columns section">
  <%= form_tag flights_path, method: 'get', class: 'bg-translucent column is-4 is-offset-1' do %>
    <h2 class="title is-2">Search for Flight</h2>
    <div class="field column has-text-centered">
      <label for="departing" class="label">Departing</label>
      <div class="control column is-8 is-offset-2">
          <%= select_tag(:departing, 
            options_for_select(@departures, selected: params[:departing]), 
            class: 'select is-fullwidth',
            required: true, 
            include_blank: true) %>
      </div>

      <label for="arriving" class="label">Arriving</label>
      <div class="control column is-8 is-offset-2">
        <%= select_tag(:arriving, 
          options_for_select(@arrivals, selected: params[:arriving]),
          class: 'select is-fullwidth', 
          required: true, 
          include_blank: true) %>
      </div>

      <label for="date" class="label">Date</label>
      <div class="control column is-8 is-offset-2">
        <%= select_tag(:date, 
          options_for_select(@dates, selected: params[:date]),
          class: 'select is-fullwidth', 
          required: true,
          include_blank: true) %>
      </div>

    <label for="passengers" class="label">Number of Passengers</label>
    <div class="control column is-8 is-offset-2">
      <%= select_tag(:passengers,
        options_for_select(@passengers, selected: params[:passengers]),
        class: 'select is-fullwidth',
        required: true,
        include_blank: true) %>
    </div>

      <%= submit_tag "Search", class: 'button is-info' %>
    </div>
  <% end %>
  <% unless @flights.nil? %>
    <% if @flights.length > 0 %>
      <div class="column is-4 is-offset-2 bg-translucent has-text-centered fit-content" id="select-flight">
        <h2 class="title is-2">Select A Flight</h2><br />
        <table>
          <thead>
            <th></th>
            <th>Flight No.</th>
            <th>Departing</th>
            <th>Date</th>
            <th>Time</th>
          </thead>
          <tbody>
            <%= form_tag(new_booking_path, method: 'get') do %>
              <% @flights.each do |f| %>
                <tr>
                  <td><%= radio_button_tag(:selected, f.id) %></td>
                  <td><%= f.number %></td>
                  <td><%= f.departure.code + ' > ' + f.arrival.code%></td>
                  <td><%= f.departure_time.to_time.strftime("%b %d %Y") %></td>
                  <td><%= f.departure_time.strftime("%I:%M %P") %></td>
                </tr>
              <% end %>
          </tbody>
        </table>
        <%= hidden_field_tag :passengers, params[:passengers] %>
        <%= submit_tag "Continue to Booking", class: 'button is-primary has-margins' %>
        <% end %>
      </div>

    <% elsif params[:commit] == "Search" %>
      <div class="column is-4 is-offset-2 bg-translucent fit-content is-centered-virtical">
        <h2 class="title is-4">Could not Find Matching Flight</h2>
        <h2 class="title is-4">Please try again</h2>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="body">
      <%= yield %>
    </div>
  </body>
</html>